-- Thêm ROLE_CUSTOMER vào ENUM trước
ALTER TABLE `user_roles`
  MODIFY COLUMN `role` ENUM('ROLE_USER', 'ROLE_CUSTOMER', 'ROLE_SALE', 'ROLE_WAREHOUSE', 'ROLE_ADMIN') NOT NULL;

ALTER TABLE `notifications`
  MODIFY COLUMN `target_role` ENUM('ROLE_USER', 'ROLE_CUSTOMER', 'ROLE_SALE', 'ROLE_WAREHOUSE', 'ROLE_ADMIN') NULL DEFAULT NULL;

-- Cập nhật dữ liệu từ ROLE_USER sang ROLE_CUSTOMER
UPDATE `user_roles` SET `role` = 'ROLE_CUSTOMER' WHERE `role` = 'ROLE_USER';
UPDATE `notifications` SET `target_role` = 'ROLE_CUSTOMER' WHERE `target_role` = 'ROLE_USER';

-- Xóa ROLE_USER khỏi ENUM
ALTER TABLE `user_roles`
  MODIFY COLUMN `role` ENUM('ROLE_CUSTOMER', 'ROLE_SALE', 'ROLE_WAREHOUSE', 'ROLE_ADMIN') NOT NULL;

ALTER TABLE `notifications`
  MODIFY COLUMN `target_role` ENUM('ROLE_CUSTOMER', 'ROLE_SALE', 'ROLE_WAREHOUSE', 'ROLE_ADMIN') NULL DEFAULT NULL;
