spring:
  application:
    name: Sneaker Api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    clean-disabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            scope: email,profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            client-name: Google

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}
  forward-headers-strategy: framework

application:
  cors:
    allowed-methods: [ GET, POST, PUT, DELETE, PATCH, OPTIONS ]
    allowed-headers: [ "*" ]
    allow-credentials: true
    max-age: 1h

  security:
    jwt:
      issuer: sneaker-api
      access:
        expiration: ${JWT_ACCESS_EXPIRATION:PT10M}
      refresh:
        expiration: ${JWT_REFRESH_EXPIRATION:P7D}
      reset-password:
        expiration: ${JWT_RESET_PASSWORD_EXPIRATION:PT15M}
